#include "pch.h"

#include <chrono>
#include <forward_list>
#include <vector>
#include <list>
#include <stack>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <deque>
#include <string>
#include <memory>
#include <array>
#include <tuple>
#include <functional>
#include <random>
#include <cstdint>
#include <cfloat>
#include <cstdio>
#include <cstdlib>
#include <cctype>
#include <cstdarg>
#include <ctime>
#include <cerrno>
#include <clocale>
#include <cstring>
#define _USE_MATH_DEFINES
#include <cmath>
#include <cassert>
#include <limits>
#include <algorithm>
#include <locale>
#include <stdexcept>
#include <exception>
#include <atomic>
#include <mutex>
#include <thread>
#include <sstream>
#include <iostream>
#include <fstream>
#include <regex>
