//line 3868
// inside enum e_state {
#ifdef LEMONEX
  ,
  WAITING_FOR_INTEGRATIONMODE_1,
  WAITING_FOR_INTEGRATIONMODE_2,
  WAITING_FOR_NESTINGDEPTH_1,
  WAITING_FOR_NESTINGDEPTH_2,
  WAITING_FOR_ENCODING_ID_1,
  WAITING_FOR_ENCODING_ID_2,
  WAITING_FOR_ARROW_LEX,
  IN_REGEX,
  IN_NEXTMODE,
  NEXT_MODE_1,
  WAITING_FOR_MODE_ID_1,
  WAITING_FOR_MODE_ID_2,
  WAITING_FOR_DEBUG_LEVEL_1,
  WAITING_FOR_DEBUG_LEVEL_2,
#endif
